version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    env_file:
      - env/.env.example
    environment:
      DATABASE_URL: mysql+aiomysql://ecommerce:ecommerce@db:3306/mini_ecommerce
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    env_file:
      - env/.env.frontend.example
    environment:
      VITE_API_BASE_URL: http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
